### PR TITLE
fix: set interpolation macro/filter titles to match the actual function name

### PR DESCRIPTION
**Pull request by lmossman**
## What

I am currently working on implementing the UI changes for [this issue](https://github.com/airbytehq/airbyte-internal-issues/issues/10588), to add a pop-up menu listing the various interpolation variables and functions that are available to the user.

Here is what the draft implementation currently looks like for `variables`:
Screenshot 2024-11-19 at 10 21 37 AM

The contents of this menu come from the [interpolation section](https://github.com/airbytehq/airbyte-python-cdk/blob/19afe5a1400e38e8cae0627a6be8a3bd4d254e4a/airbyte_cdk/sources/declarative/declarative_component_schema.yaml#L2703-L2892) of the declarative component schema.

However, there is a problem: the `title`s of the macros and filters in that section do not match the actual function names, and the function names don't appear anywhere else in that section. So, the UI doesn't know what text to actually insert into the input when the user selects one of these.

## How

This PR solves the issue by renaming the titles to match the actual function names themselves.

The UI can then use the title to populate the list and also to insert directly into the input upon selection, just like it does with the variables.

## Open Questions
- Does this change affect any other code? As far as I can tell, only the documentation uses this part of the YAML today to populate [these docs](https://docs.airbyte.com/connector-development/config-based/understanding-the-yaml-file/reference#variables), in which case this should be a safe change as it will just cause the titles of each section to match the function names themselves.

## Summary by CodeRabbit

- **New Features**
	- Introduced new components for authentication, pagination, and error handling, enhancing the flexibility and robustness of data extraction.
	- Added detailed schema definitions for various components, improving clarity and usability for developers.

- **Improvements**
	- Expanded error handling capabilities with new error handler definitions.
	- Enhanced pagination strategies with new options for better data management.
	- Refined existing components for improved functionality and clarity.

### CODE REVIEW

**Review by aaronsteers — APPROVED** [review]
Approved for my part - based on my review of the code changes and the PR description explaining the input. Since I'm not deep on this part of the codebase, you may opt to wait for another pair of eyes. Your call, but to me it looks good. 🚀

**Comment by lmossman** [comment]
@natikgadzhi No idea - my PR did not touch it

**Comment by natikgadzhi** [comment]
@lmossman good to merge — @maxi297 works on chargebee problem separately. 

@aaronsteers @ChristoGrab we ready to merge and ship the CDK version? Will release work and publish to pypi, and publish SDM alongside it? ;)

**Comment by maxi297** [comment]
For chargebee, the fixes will be available on https://github.com/airbytehq/airbyte/pull/48510 so that's fine

**Pull request merged**
