### PR TITLE
fix(manifest-connectors): resolve parsing errors during version comparisons

### PR DESCRIPTION
**Pull request by aaronsteers**
## Summary by CodeRabbit

- **New Features**
	- Introduced the `source-chargebee` connector to the testing workflow, enhancing the range of connectors tested.

- **Bug Fixes**
	- Improved job efficiency by aborting unnecessary tests based on changes in specified connectors.

- **Improvements**
	- Enhanced version validation logic for manifest files, providing clearer error handling and feedback regarding version compatibility.
	- Expanded test coverage for manifest configurations, improving validation and error handling for various scenarios.

### CODE REVIEW

**Review by pnilan — APPROVED** [review]
LGTM

**Comment by aaronsteers** [comment]
The manifest connector runs a version comparison that was not handling the pre-release part of a version number. 

image

Resolving by parsing with `version.Version` from the packaging library.

**Pull request merged**
