### PR TITLE
chore(docs): purge sphinx documentation and related dependencies

### LINKED ISSUE #123: Clean out sphinx-related deps and old reference docs.
Delete sphinx-related docs generation:
- sphinx-related dependencides
- sphinx-docs.md
- reference_docs directory
- Other general loose ends cleanup

### PR DESCRIPTION
**Pull request by arr-ee**
Fixes #123.

Please note that `poetry.lock` includes changes from #126 since I can't preserve its being out of sync.

I assume that whatever job was publishing these docs only existed in the previous incarnation of this repo since I can't find any traces of it in git log, so there might be more cleanup needed to remove previously published docs.

## Summary by CodeRabbit

- **Chores**
	- Removed the `sphinx-docs` extra dependency from the project configuration.
	- Deleted various documentation files related to the Airbyte CDK, including API references and configuration files for documentation generation.
	- Improved formatting and readability of the project configuration file.

These changes enhance the overall organization and clarity of the project documentation, although some documentation resources have been removed.

### CODE REVIEW

**Comment by natikgadzhi** [comment]
I've nuked the corresponding readthedocs site. They didn't have options to setup a proper redirect, and we didn't have any traffic there. Good riddance.

**Review by aaronsteers — APPROVED** [review]
NICE! :shipit:

**Pull request merged**
